apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: paankaur/query:latest
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: NodePort
  ports:
    - name: query
      protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30004
